apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp-devops-gke
  labels:
    app: gcp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gcp
  template:
    metadata:
      labels:
        app: gcp
    spec:
      containers:
      - name: gcp-devops-gke
        image: gcr.io/primal-arcadia-387902/gcpdevops
        ports:
        - containerPort: 5000
        env:
          - name: PORT 
            value: "5000" 